---
title: "'Throw' 피연산자는 'System.Exception'에서 파생되어야 합니다."
ms.date: 07/20/2015
f1_keywords:
- vbc30665
- bc30665
helpviewer_keywords:
- BC30665
ms.assetid: 7c228087-39ea-4b30-a410-6ba711e67e5e
ms.openlocfilehash: 71727cc191f8ab1663589e64fb9ee5ce076684f4
ms.sourcegitcommit: 2701302a99cafbe0d86d53d540eb0fa7e9b46b36
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 04/28/2019
ms.locfileid: "64646423"
---
# <a name="throw-operand-must-derive-from-systemexception"></a>'Throw' 피연산자는 'System.Exception'에서 파생되어야 합니다.
`Throw` 에 제공된 인수는 `System.Exception` 인스턴스 또는 `System.Exception`에서 파생된 클래스의 인스턴스여야 합니다.  
  
 **오류 ID:** BC30665  
  
## <a name="to-correct-this-error"></a>이 오류를 해결하려면  
  
- 다음 예제와 같이 `System.Exception`에서 파생된 인수를 사용합니다.  
  
    ```vb
    Throw New System.Exception("This is an error.")  
    ```  
  
## <a name="see-also"></a>참고자료

- [Throw 문](../../visual-basic/language-reference/statements/throw-statement.md)
- [Try...Catch...Finally 문](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
- <xref:System.Exception?displayProperty=nameWithType>
- [.NET의 예외 처리 및 Throw](../../standard/exceptions/index.md)
