---
title: "'Catch'는 'Try' 문 외부에 사용할 수 없습니다."
ms.date: 07/20/2015
f1_keywords:
- bc30380
- vbc30380
helpviewer_keywords:
- BC30380
ms.assetid: 73ce950d-881f-4532-8024-40a4930abd32
ms.openlocfilehash: f9ce965d1d983743796f8cc66ae20ffb018a07bc
ms.sourcegitcommit: 9b552addadfb57fab0b9e7852ed4f1f1b8a42f8e
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 04/23/2019
ms.locfileid: "62027539"
---
# <a name="catch-cannot-appear-outside-a-try-statement"></a>'Catch'는 'Try' 문 외부에 사용할 수 없습니다.
`Catch` 는 `Try...Catch...Finally` 문 블록 내에서 사용해야 합니다. 불필요한 `Catch` 문이 `Try` 블록에 있거나, `Catch` 문이 해당 `Try` 블록의 경계 외부에 나타납니다.  
  
 **오류 ID:** BC30380  
  
## <a name="to-correct-this-error"></a>이 오류를 해결하려면  
  
1. 필요하지 않은 경우 `Catch` 문을 삭제하거나, `Try...Catch...Finally` 문 블록 내에 배치합니다.  
  
## <a name="see-also"></a>참고자료

- [Try...Catch...Finally 문](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
